FROM python:3.12-slim

RUN apt-get update
RUN apt-get install -y ffmpeg

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY *.py /app/
COPY docker/run.sh /app/
COPY web_assets /app/web_assets

RUN chmod +x /app/*.sh

VOLUME ["/data"]

CMD ["/app/run.sh"]
